name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: Yu-0n/Yu-0n
          
          SECTION_NAME: waka
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_TOTAL: true

          TARGET_BRANCH: master
          TARGET_PATH: README.md
